version: "3.1"

services:
  database:
    container_name: "codename"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: codename
      POSTGRES_PASSWORD: codename
      POSTGRES_DB: codename
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  redis:
    container_name: "redis"
    image: "redis"
    ports:
      - "6379:6379"
  # vault:
  #   image: vault:latest
  #   volumes:
  #     - ./vault/config:/vault/config
  #     - ./vault/policies:/vault/policies
  #     - ./vault/data:/vault/data
  #   ports:
  #     - 8200:8200
  #   environment:
  #     - VAULT_ADDR=http://0.0.0.0:8200
  #     - VAULT_API_ADDR=http://0.0.0.0:8200
  #     - VAULT_ADDRESS=http://0.0.0.0:8200
  #     - HISTIGNORE="&:vault*"
  #   cap_add:
  #     - IPC_LOCK
  #   command: vault server -config=/vault/config/vault.json
