version: "3.1"

services:
  database:
    container_name: "bob"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: bob
      POSTGRES_DB: bob
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  redis:
    container_name: "redis"
    image: "redis"
    ports:
      - "6379:6379"